package tp.location;

/**
* tp/location/LocationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tp.idl
* vendredi 23 décembre 2016 17 h 37 WET
*/

public final class LocationHolder implements org.omg.CORBA.portable.Streamable
{
  public tp.location.Location value = null;

  public LocationHolder ()
  {
  }

  public LocationHolder (tp.location.Location initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tp.location.LocationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tp.location.LocationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tp.location.LocationHelper.type ();
  }

}
