package tp.location;


/**
* tp/location/LocationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tp.idl
* vendredi 23 décembre 2016 17 h 37 WET
*/

public interface LocationOperations 
{
  int d ();
  void d (int newD);
  void louer ();
} // interface LocationOperations
