package tp.location;


/**
* tp/location/LocationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tp.idl
* vendredi 23 décembre 2016 17 h 37 WET
*/

public abstract class LocationPOA extends org.omg.PortableServer.Servant
 implements tp.location.LocationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_d", new java.lang.Integer (0));
    _methods.put ("_set_d", new java.lang.Integer (1));
    _methods.put ("louer", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // tp/location/Location/_get_d
       {
         int $result = (int)0;
         $result = this.d ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // tp/location/Location/_set_d
       {
         int newD = in.read_long ();
         this.d (newD);
         out = $rh.createReply();
         break;
       }

       case 2:  // tp/location/Location/louer
       {
         this.louer ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:tp/location/Location:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Location _this() 
  {
    return LocationHelper.narrow(
    super._this_object());
  }

  public Location _this(org.omg.CORBA.ORB orb) 
  {
    return LocationHelper.narrow(
    super._this_object(orb));
  }


} // class LocationPOA
