package tp.restitution;


/**
* tp/restitution/Restitution.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tp.idl
* vendredi 23 décembre 2016 17 h 37 WET
*/

public interface Restitution extends RestitutionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Restitution
