package tp.restitution;

/**
* tp/restitution/RestitutionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tp.idl
* vendredi 23 décembre 2016 17 h 37 WET
*/

public final class RestitutionHolder implements org.omg.CORBA.portable.Streamable
{
  public tp.restitution.Restitution value = null;

  public RestitutionHolder ()
  {
  }

  public RestitutionHolder (tp.restitution.Restitution initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tp.restitution.RestitutionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tp.restitution.RestitutionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tp.restitution.RestitutionHelper.type ();
  }

}
