package tp.restitution;


/**
* tp/restitution/RestitutionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tp.idl
* vendredi 23 décembre 2016 17 h 37 WET
*/

public interface RestitutionOperations 
{
  int r ();
  void r (int newR);
  int n ();
  void restituer ();
} // interface RestitutionOperations
